// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBet8jlRH8y4CCcK5vJXDb1gXVxDckkQFU',
//     appId: '1:707482024414:web:22b0e2ab83fe3d5437854f',
//     messagingSenderId: '707482024414',
//     projectId: 'chatting-532e6',
//     authDomain: 'chatting-532e6.firebaseapp.com',
//     storageBucket: 'chatting-532e6.firebasestorage.app',
//     measurementId: 'G-7KCVKNQDF1',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBupwMPeTiv7VFAUm_9faxW4D3kqIayhYo',
//     appId: '1:707482024414:android:996626713be5049d37854f',
//     messagingSenderId: '707482024414',
//     projectId: 'chatting-532e6',
//     storageBucket: 'chatting-532e6.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA61PH5vC89dsN8YieVTu3jcPYrNAebiGM',
//     appId: '1:707482024414:ios:2777e0569940e44637854f',
//     messagingSenderId: '707482024414',
//     projectId: 'chatting-532e6',
//     storageBucket: 'chatting-532e6.firebasestorage.app',
//     iosBundleId: 'com.example.chat',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyA61PH5vC89dsN8YieVTu3jcPYrNAebiGM',
//     appId: '1:707482024414:ios:2777e0569940e44637854f',
//     messagingSenderId: '707482024414',
//     projectId: 'chatting-532e6',
//     storageBucket: 'chatting-532e6.firebasestorage.app',
//     iosBundleId: 'com.example.chat',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBet8jlRH8y4CCcK5vJXDb1gXVxDckkQFU',
//     appId: '1:707482024414:web:03cf424df664bbe237854f',
//     messagingSenderId: '707482024414',
//     projectId: 'chatting-532e6',
//     authDomain: 'chatting-532e6.firebaseapp.com',
//     storageBucket: 'chatting-532e6.firebasestorage.app',
//     measurementId: 'G-MBDTMY6X98',
//   );
// }
